server:
  port: 8081
  
spring:
    application:
      name: paymentservice
      
eureka: 
  client: 
    serviceUrl: 
      defaultZone: ${EUREKA_URI:http://localhost:8088/eureka}
      
            
    
    